/* eslint-disable prettier/prettier */
/*
 * action 类型
 */
export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  INFO_INIT: 'INFO_INIT',
  TOKEN_INIT: 'TOKEN_INIT',
  STUDY_DATA_REFERSH: 'STUDY_DATA_REFRESH',
  STUDY_REFERSH_SUCCESS: 'STUDY_REFRESH_SUCCESS',
  STUDY_REFRESH_FAIL: 'STUDY_REFRESH_FAIL',
  STUDY_LOAD_MORE: 'STUDY_LOAD_MORE',
  STUDY_LOAD_MORE_SUCCESS: 'STUDY_LOAD_MORE_SUCCESS',
  STUDY_LOAD_MORE_FAIL: 'STUDY_LOAD_MORE_FAIL',
  EXAM_EMPTY_SIZE: 'EXAM_EMPTY_SIZE',
};
